services:
  inventoris_toko:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventoris_toko
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_ENV: production
      APP_DEBUG: false
      PORT: 80
    volumes:
      - app_logs:/app/logs
    networks:
      - web

volumes:
  app_logs:

networks:
  web:
    external: true
